---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: {{ CLUSTER_NAME }}
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: [{{ POD_CIDR }}]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPI_VERSION }}
    kind: Metal3Cluster
    name: {{ CLUSTER_NAME }}
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: {{ CLUSTER_NAME }}-controlplane
---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPI_VERSION }}
kind: Metal3Cluster
metadata:
  name: {{ CLUSTER_NAME }}
spec:
  controlPlaneEndpoint:
    host: {{ CLUSTER_APIENDPOINT_HOST }}
    port: 6443
  noCloudProvider: false
