{% if CAPI_VERSION == 'v1alpha2' %}
apiVersion: cluster.x-k8s.io/v1alpha2
{% else %}
apiVersion: cluster.x-k8s.io/v1alpha3
{% endif %}
kind: MachineDeployment
metadata:
  name: {{ CLUSTER_NAME }}-md-0
  labels:
    cluster.x-k8s.io/cluster-name: {{ CLUSTER_NAME }}
    nodepool: nodepool-0
spec:
{% if CAPI_VERSION != 'v1alpha2' %}
  clusterName: {{ CLUSTER_NAME }}
{% endif %}
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ CLUSTER_NAME }}
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ CLUSTER_NAME }}
        nodepool: nodepool-0
    spec:
{% if CAPI_VERSION != 'v1alpha2' %}
      clusterName: {{ CLUSTER_NAME }}
{% endif %}
      version: {{ KUBERNETES_VERSION }}
      bootstrap:
        configRef:
          name: {{ CLUSTER_NAME }}-md-0
          apiVersion: bootstrap.cluster.x-k8s.io/{{ CAPI_VERSION }}
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: {{ CLUSTER_NAME }}-md-0
        apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPI_VERSION }}
{% if CAPI_VERSION == 'v1alpha2' %}
        kind: BareMetalMachineTemplate
{% else %}
        kind: Metal3MachineTemplate
{% endif %}
---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPI_VERSION }}
{% if CAPI_VERSION == 'v1alpha2' %}
kind: BareMetalMachineTemplate
{% else %}
kind: Metal3MachineTemplate
{% endif %}
metadata:
  name: {{ CLUSTER_NAME }}-md-0
spec:
  template:
    spec:
      image:
        url: {{ IMAGE_URL }}
        checksum: {{ IMAGE_CHECKSUM }}
---
{% if CAPI_VERSION == 'v1alpha2' %}
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
{% else %}
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
{% endif %}
kind: KubeadmConfigTemplate
metadata:
  name: {{ CLUSTER_NAME }}-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: {{ " '{{ ds.meta_data.name }}' " }}
          kubeletExtraArgs:
            node-labels: 'metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}'
            provider-id: 'metal3://{{ '{{ ds.meta_data.uuid }}' }}'
      preKubeadmCommands:
        - ifup eth1
        - mv /tmp/akeys /home/centos/.ssh/authorized_keys
        - chown centos:centos /home/centos/.ssh/authorized_keys
        - yum update -y
        - yum install yum-utils device-mapper-persistent-data lvm2 -y
        - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        - setenforce 0
        - sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
        - yum install docker-ce docker-ce-cli --disableexcludes=kubernetes --nobest -y
        - yum install kubelet kubeadm kubectl --disableexcludes=kubernetes -y
        - usermod -aG docker centos
        - systemctl enable --now docker kubelet
      files:
        - path: /etc/sysconfig/network-scripts/ifcfg-eth1
          owner: root:root
          permissions: '0644'
          content: |
            BOOTPROTO=dhcp
            DEVICE=eth1
            ONBOOT=yes
            TYPE=Ethernet
            USERCTL=no
        - path: /etc/yum.repos.d/kubernetes.repo
          owner: root:root
          permissions: '0644'
          content: |
            [kubernetes]
            name=Kubernetes
            baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
            enabled=1
            gpgcheck=1
            repo_gpgcheck=0
            gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        - path: /tmp/akeys
          owner: root:root
          permissions: '0600'
          content: {{ SSH_PUB_KEY_CONTENT }}
