apiVersion: cluster.x-k8s.io/v1alpha2
kind: MachineDeployment
metadata:
  name: ${CLUSTER_NAME}-md-0
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    nodepool: nodepool-0
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
        nodepool: nodepool-0
    spec:
      version: ${KUBERNETES_VERSION}
      bootstrap:
        configRef:
          name: ${CLUSTER_NAME}-md-0
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: ${CLUSTER_NAME}-md-0
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: BareMetalMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: BareMetalMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  template:
    spec:
      image:
        url: ${IMAGE_URL}
        checksum: ${IMAGE_CHECKSUM}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.name }}'
          kubeletExtraArgs:
            node-labels: 'metal3.io/uuid={{ ds.meta_data.uuid }},metal3.io/namespace={{ ds.meta_data.metal3-namespace }},metal3.io/name={{ ds.meta_data.metal3-name }}'
      preKubeadmCommands:
        - ifup eth1
        - yum check-update
        - yum update -y
        - yum install -y yum-utils device-mapper-persistent-data lvm2
        - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        - yum install docker-ce-18.09.9 docker-ce-cli-18.09.9 containerd.io -y
        - usermod -aG docker centos
        - systemctl start docker
        - systemctl enable docker
        - setenforce 0
        - sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
        - yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
        - systemctl enable --now kubelet
      files:
        - path: /etc/sysconfig/network-scripts/ifcfg-eth1
          owner: root:root
          permissions: '0644'
          content: |
            BOOTPROTO=dhcp
            DEVICE=eth1
            ONBOOT=yes
            TYPE=Ethernet
            USERCTL=no
        - path: /etc/yum.repos.d/kubernetes.repo
          owner: root:root
          permissions: '0644'
          content: |
            [kubernetes]
            name=Kubernetes
            baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
            enabled=1
            gpgcheck=1
            repo_gpgcheck=0
            gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        - path: /home/centos/.ssh/authorized_keys
          owner: centos:centos
          permissions: '0600'
          content: ${SSH_PUB_KEY_CONTENT}
