---

- set_fact:
    generate_vm_nodes: "{{vm_nodes is not defined}}"

- name: Define vm_nodes if not already defined
  when: generate_vm_nodes
  include_tasks: vm_nodes_tasks.yml
  loop: "{{flavors|dict2items}}"
  loop_control: 
    loop_var: flavor

- debug:
    var: vm_nodes
  when: generate_vm_nodes

# Describe our virtual networks.  These networks will be attached to
# the vm nodes in the order in which they are defined with the following caveats:
#   *  The first bridge network defined will be used for pxe booting
- set_fact:
    generate_networks: "{{networks is not defined}}"
- name: Define networks when not already defined
  when: generate_networks
  block:
    - name: Set fact for networks
      set_fact:
        networks:
          - name: provisioning
            bridge: provisioning
            forward_mode: bridge
          - name: baremetal
            bridge: baremetal
            forward_mode: "{% if manage_baremetal == 'y' %}nat{% else %}bridge{% endif %}"
            address: "{{ baremetal_network_cidr|nthhost(1) }}"
            netmask: "{{ baremetal_network_cidr|ipaddr('netmask') }}"
            dhcp_range:
              - "{{ baremetal_network_cidr|nthhost(20) }}"
              - "{{ baremetal_network_cidr|nthhost(60) }}"
            nat_port_range:
              - 1024
              - 65535
            domain: "{{ cluster_domain }}"
            dns:
              hosts: "{{dns_extrahosts | default([])}}"
              forwarders:
                - domain: "apps.{{ cluster_domain }}"
                  addr: "127.0.0.1"
