- name: "iptables: Firewalld service stopped"
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: True

- name: "iptables: VBMC Ports"
  iptables:
    chain: INPUT
    in_interface: "{{ baremetal_interface }}"
    protocol: udp
    match: udp
    destination_port: "{{ vbmc_port_range }}"
    jump: ACCEPT

- name: "iptables: Established and related"
  iptables:
    chain: FORWARD
    in_interface: "{{ provisioning_interface }}"
    match: conntrack
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: "iptables: Ironic Ports"
  iptables:
    chain: FORWARD
    in_interface: "{{ provisioning_interface }}"
    protocol: tcp
    match: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop: "{{ ironic_ports }}"

- name: "iptables: Provisioning host ports"
  iptables:
    chain: INPUT
    in_interface: "{{ provisioning_interface }}"
    protocol: tcp
    match: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop: "{{ provisioning_host_ports }}"

- name: "iptables: PXE Ports"
  iptables:
    chain: FORWARD
    in_interface: "{{ provisioning_interface }}"
    protocol: udp
    match: udp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop: "{{ pxe_udp_ports }}"

- name: "iptables: Ironic Endpoint Keepalived"
  iptables:
    chain: FORWARD
    in_interface: "{{ provisioning_interface }}"
    protocol: "{{ item }}"
    jump: ACCEPT
  loop: "{{ ironic_keepalived_proto }}"

- name: "iptables: Allow access to baremetal network from kind"
  iptables:
    chain: FORWARD
    action: insert
    out_interface: "{{ baremetal_interface }}"
    destination: "192.168.111.1/24"
    jump: ACCEPT
  when: (EPHEMERAL_CLUSTER == "kind")
