---
- name: v1alpha2 integration test
  hosts: virthost
  connection: local
  gather_facts: true
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - import_role:
        name: v1a2_integration_test
