---
  - name: Remove temporary Ubuntu crs
    file:
      path: "/tmp/{{ item }}.yaml"
      state: absent
    with_items:
      - controlplane_ubuntu
      - workers_ubuntu
    when: IMAGE_OS == "Ubuntu"

  - name: Remove temporary CentOS crs
    file:
      path: "/tmp/{{ item }}.yaml"
      state: absent
    with_items:
      - controlplane_centos
      - workers_centos
    when: (IMAGE_OS == "Centos") or
          (IMAGE_OS == "")

  - name: Check if cluster deprovisioning started.
    shell: "kubectl get cluster -n {{ NAMESPACE }} -o json | jq -r '.items[] | .status.phase'"
    register: deprovision_cluster
    retries: 2
    delay: 20
    until: (deprovision_cluster.stdout == "deleting") or
           (deprovision_cluster.stdout == "Deleting") or
           (deprovision_cluster.stdout == "")

  - name: Wait until both bmh becomes ready again.
    shell: |
        kubectl get bmh -n {{ NAMESPACE }} -o json | jq -r '.items[] |
        select (.status.provisioning.state == "ready") |
        .metadata.name'
    register: deprovisioned_nodes
    retries: 150
    delay: 3
    until: deprovisioned_nodes.stdout_lines ==  ["node-0", "node-1"]
