---
  - name: Deprovision Ubuntu based worker node
    block:
      - name: Copy generated controlplane_ubuntu.yaml
        copy:
          src: "{{ TEMP_GEN_DIR }}/{{ CAPI_VERSION }}_workers_ubuntu.yaml"
          dest: "/tmp/workers_ubuntu.yaml"

      - name: Deprovision Ubuntu worker node.
        k8s:
          state: absent
          src: "/tmp/workers_ubuntu.yaml"
          namespace: "{{ NAMESPACE }}"
        ignore_errors: yes
        register: deprovision_ubuntu_worker_node
    when: IMAGE_OS == "Ubuntu"

  - name: Deprovision CentOS based worker node
    block:
      - name: Copy generated controlplane_ubuntu.yaml
        copy:
          src: "{{ TEMP_GEN_DIR }}/{{ CAPI_VERSION }}_workers_centos.yaml"
          dest: "/tmp/workers_centos.yaml"

      - name: Deprovision CentOS worker node.
        k8s:
          state: absent
          src: "/tmp/workers_centos.yaml"
          namespace: "{{ NAMESPACE }}"
        ignore_errors: yes
        register: deprovision_centos_worker_node
    when: (IMAGE_OS == "Centos") or
          (IMAGE_OS == "")
