---
  - name: Switch Ansible's Python interpreter to Python 3
    set_fact:
      ansible_python_interpreter: /usr/bin/python3

  - name: Deprovision Ubuntu worker node.
    k8s:
      state: absent
      src: "/tmp/workers_ubuntu.yaml"
      namespace: "{{ NAMESPACE }}"
    register: deprovision_ubuntu_worker_node
    when: IMAGE_OS == "Ubuntu"

  - name: Deprovision CentOS worker node.
    k8s:
      state: absent
      src: "/tmp/workers_centos.yaml"
      namespace: "{{ NAMESPACE }}"
    register: deprovision_centos_worker_node
    when: (IMAGE_OS == "Centos") or
          (IMAGE_OS == "")
