---
  - name: Switch Ansible's Python interpreter to Python 3
    set_fact:
      ansible_python_interpreter: /usr/bin/python3

  - name: Deprovision cluster
    k8s:
      state: absent
      src: "/tmp/cluster.yaml"
      namespace: "{{ NAMESPACE }}"
    register: deprovision_cluster
