---
  - name: Template cluster.yaml
    template:
      src: "{{ CRS_PATH }}/cluster.yaml"
      dest: "/tmp/cluster.yaml"

  - name: Deprovision cluster
    k8s:
      state: absent
      src: "/tmp/cluster.yaml"
      namespace: "{{ NAMESPACE }}"
    ignore_errors: yes
    register: deprovision_cluster
