---
  - name: Template cluster.yaml for v1alpha3
    template:
      src: "{{ TEMP_GEN_DIR }}/{{ CAPI_VERSION }}_cluster_{{ CLUSTER_NAME }}_{{ IMAGE_OS|lower }}.yaml"
      dest: "/tmp/cluster.yaml"

  - name: Deprovision cluster
    k8s:
      state: absent
      src: "/tmp/cluster.yaml"
      namespace: "{{ NAMESPACE }}"
    ignore_errors: yes
    register: deprovision_cluster
