---
- name: "{{ CAPI_VERSION }} deployment"
  include: "{{ item }}.yml"
  with_items:
    - provision_cluster
    - provision_controlplane
    - provision_worker
    - verify
    - deprovision_worker
    - deprovision_controlplane
    - deprovision_cluster
    - pause
  when: RUN_CI_TEST == "true"

- name: "{{ CAPI_VERSION }} cluster provisioning"
  include: "provision_cluster.yml"
  when: PROVISION_CLUSTER == "true"

- name: "{{ CAPI_VERSION }} controlplane node provisioning"
  include: "provision_controlplane.yml"
  when: PROVISION_CONTROLPLANE == "true"

- name: "{{ CAPI_VERSION }} worker node provisioning"
  include: "provision_worker.yml"
  when: PROVISION_WORKER == "true"

- name: "{{ CAPI_VERSION }} cluster deprovisioning"
  include: deprovision_cluster.yml
  when: DEPROVISION_CLUSTER == "true"

- name: "{{ CAPI_VERSION }} controlplane node deprovisioning"
  include: deprovision_controlplane.yml
  when: DEPROVISION_CONTROLPLANE == "true"

- name: "{{ CAPI_VERSION }} worker node deprovisioning"
  include: deprovision_worker.yml
  when: DEPROVISION_WORKER == "true"
