---
- name: "{{ CAPI_VERSION }} deployment"
  include: "{{ item }}.yml"
  with_items:
    - provision_cluster
    - provision_controlplane
    - provision_worker
    - verify
    - deprovision_worker
    - deprovision_controlplane
    - deprovision_cluster
    - pause
  when: v1aX_integration_test_action == "ci_test"

- name: "{{ CAPI_VERSION }} cluster provisioning"
  include: "provision_cluster.yml"
  when: v1aX_integration_test_action == "provision_cluster"

- name: "{{ CAPI_VERSION }} controlplane node provisioning"
  include: "provision_controlplane.yml"
  when: v1aX_integration_test_action == "provision_controlplane"

- name: "{{ CAPI_VERSION }} worker node provisioning"
  include: "provision_worker.yml"
  when: v1aX_integration_test_action == "provision_worker"

- name: "{{ CAPI_VERSION }} cluster deprovisioning"
  include: deprovision_cluster.yml
  when: v1aX_integration_test_action == "deprovision_cluster"

- name: "{{ CAPI_VERSION }} controlplane node deprovisioning"
  include: deprovision_controlplane.yml
  when: v1aX_integration_test_action == "deprovision_controlplane"

- name: "{{ CAPI_VERSION }} worker node deprovisioning"
  include: deprovision_worker.yml
  when: v1aX_integration_test_action == "deprovision_worker"
