---
  - name: Install openshift client in CentOS 8 using pip3
    pip:
      executable: "pip3"
      name: openshift
      state: present
    become: true
    become_user: root
    when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == '8'

  - name: Install openshift client in CentOS 7 using pip
    pip:
      executable: "pip"
      name: openshift
      state: present
    become: true
    become_user: root
    when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == '7'

  - name: Template cluster.yaml
    copy:
      src: "{{ TEMP_GEN_DIR }}/{{ CAPI_VERSION }}_cluster_{{ CLUSTER_NAME }}_{{ IMAGE_OS|lower }}.yaml"
      dest: "/tmp/cluster.yaml"

  - name: Provision cluster
    k8s:
      state: present
      src: "/tmp/cluster.yaml"
      namespace: "{{ NAMESPACE }}"
    register: provision_cluster
