---
# Provision worker node
  - name: Provision Ubuntu based worker node
    block:
      - name: Template workers_ubuntu.yaml
        template:
          src: "{{ CRS_PATH }}/workers_ubuntu.yaml"
          dest: "/tmp/workers_ubuntu.yaml"

      - name: Create Ubuntu worker node
        k8s:
          state: present
          src: "/tmp/workers_ubuntu.yaml"
          namespace: "{{ NAMESPACE }}"
        register: ubuntu_worker_node
    when: IMAGE_OS == "Ubuntu"

  - name: Provision CentOS based worker node
    block:
      - name: Template workers_centos.yaml
        template:
          src: "{{ CRS_PATH }}/workers_centos.yaml"
          dest: "/tmp/workers_centos.yaml"
        vars:
          IMAGE_NAME: '{{ IMAGE_NAME_CENTOS }}'
          IMAGE_LOCATION: '{{ IMAGE_LOCATION_CENTOS }}'
          IMAGE_USERNAME: '{{ IMAGE_USERNAME_CENTOS }}'

      - name: Create CentOS worker node
        k8s:
          state: present
          src: "/tmp/workers_centos.yaml"
          namespace: "{{ NAMESPACE }}"
        register: centos_worker_node
    when: (IMAGE_OS == "Centos") or
          (IMAGE_OS == "")
